<div style="font-family:Arial,Helvetica,sans-serif;color:#231f20;max-width:560px">
    <h2 style="margin:0 0 12px">Nueva cotización</h2>
    <p style="margin:0 0 4px"><strong><?php echo e($cotizacion->nombre); ?></strong><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($cotizacion->empresa): ?> · <?php echo e($cotizacion->empresa); ?><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></p>
    <p style="margin:0 0 4px">Teléfono: <a href="<?php echo e($cotizacion->whatsappUrl()); ?>"><?php echo e($cotizacion->telefono); ?></a> (WhatsApp)</p>
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($cotizacion->email): ?><p style="margin:0 0 4px">Correo: <?php echo e($cotizacion->email); ?></p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($cotizacion->rubro): ?><p style="margin:0 0 4px">Rubro: <?php echo e($cotizacion->rubro); ?></p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($cotizacion->origen): ?><p style="margin:0 0 12px;color:#706c64">Desde: <?php echo e($cotizacion->origen); ?></p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    <p style="margin:12px 0 4px"><strong>Pedido</strong></p>
    <div style="border:1px solid #a3a5a8;padding:12px;white-space:pre-wrap"><?php echo e($cotizacion->mensaje); ?></div>
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($cotizacion->adjuntos->isNotEmpty()): ?>
        <p style="margin:12px 0 4px"><strong>Archivos adjuntos (<?php echo e($cotizacion->adjuntos->count()); ?>)</strong>: se descargan desde el panel.</p>
        <ul style="margin:0;padding-left:18px">
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $cotizacion->adjuntos; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $adjunto): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?>
                <li><?php echo e($adjunto->nombre_original); ?> (<?php echo e($adjunto->tamanoLegible()); ?>)</li>
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
        </ul>
    <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    <p style="margin:16px 0 0"><a href="<?php echo e($panelUrl); ?>" style="background:#f9ed31;color:#231f20;padding:10px 16px;text-decoration:none;font-weight:bold">Abrir en el panel</a></p>
</div>
<?php /**PATH /Users/leonshy/hierro-metal-web-insitucional/web/resources/views/emails/cotizacion.blade.php ENDPATH**/ ?>